package com.ws.model;

public class Addfriendinfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column addfriendinfo.id
	 * @mbggenerated  Fri Jul 07 16:24:03 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column addfriendinfo.myId
	 * @mbggenerated  Fri Jul 07 16:24:03 CST 2017
	 */
	private Integer myid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column addfriendinfo.friendId
	 * @mbggenerated  Fri Jul 07 16:24:03 CST 2017
	 */
	private Integer friendid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column addfriendinfo.message
	 * @mbggenerated  Fri Jul 07 16:24:03 CST 2017
	 */
	private String message;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column addfriendinfo.sign
	 * @mbggenerated  Fri Jul 07 16:24:03 CST 2017
	 */
	private Boolean sign;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column addfriendinfo.id
	 * @return  the value of addfriendinfo.id
	 * @mbggenerated  Fri Jul 07 16:24:03 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column addfriendinfo.id
	 * @param id  the value for addfriendinfo.id
	 * @mbggenerated  Fri Jul 07 16:24:03 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column addfriendinfo.myId
	 * @return  the value of addfriendinfo.myId
	 * @mbggenerated  Fri Jul 07 16:24:03 CST 2017
	 */
	public Integer getMyid() {
		return myid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column addfriendinfo.myId
	 * @param myid  the value for addfriendinfo.myId
	 * @mbggenerated  Fri Jul 07 16:24:03 CST 2017
	 */
	public void setMyid(Integer myid) {
		this.myid = myid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column addfriendinfo.friendId
	 * @return  the value of addfriendinfo.friendId
	 * @mbggenerated  Fri Jul 07 16:24:03 CST 2017
	 */
	public Integer getFriendid() {
		return friendid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column addfriendinfo.friendId
	 * @param friendid  the value for addfriendinfo.friendId
	 * @mbggenerated  Fri Jul 07 16:24:03 CST 2017
	 */
	public void setFriendid(Integer friendid) {
		this.friendid = friendid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column addfriendinfo.message
	 * @return  the value of addfriendinfo.message
	 * @mbggenerated  Fri Jul 07 16:24:03 CST 2017
	 */
	public String getMessage() {
		return message;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column addfriendinfo.message
	 * @param message  the value for addfriendinfo.message
	 * @mbggenerated  Fri Jul 07 16:24:03 CST 2017
	 */
	public void setMessage(String message) {
		this.message = message;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column addfriendinfo.sign
	 * @return  the value of addfriendinfo.sign
	 * @mbggenerated  Fri Jul 07 16:24:03 CST 2017
	 */
	public Boolean getSign() {
		return sign;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column addfriendinfo.sign
	 * @param sign  the value for addfriendinfo.sign
	 * @mbggenerated  Fri Jul 07 16:24:03 CST 2017
	 */
	public void setSign(Boolean sign) {
		this.sign = sign;
	}
}