package com.ws.model;

import java.util.ArrayList;
import java.util.List;

public class FriendExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table friend
	 * @mbggenerated  Sun Jul 09 14:37:52 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table friend
	 * @mbggenerated  Sun Jul 09 14:37:52 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table friend
	 * @mbggenerated  Sun Jul 09 14:37:52 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table friend
	 * @mbggenerated  Sun Jul 09 14:37:52 CST 2017
	 */
	public FriendExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table friend
	 * @mbggenerated  Sun Jul 09 14:37:52 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table friend
	 * @mbggenerated  Sun Jul 09 14:37:52 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table friend
	 * @mbggenerated  Sun Jul 09 14:37:52 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table friend
	 * @mbggenerated  Sun Jul 09 14:37:52 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table friend
	 * @mbggenerated  Sun Jul 09 14:37:52 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table friend
	 * @mbggenerated  Sun Jul 09 14:37:52 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table friend
	 * @mbggenerated  Sun Jul 09 14:37:52 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table friend
	 * @mbggenerated  Sun Jul 09 14:37:52 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table friend
	 * @mbggenerated  Sun Jul 09 14:37:52 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table friend
	 * @mbggenerated  Sun Jul 09 14:37:52 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table friend
	 * @mbggenerated  Sun Jul 09 14:37:52 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andMyidIsNull() {
			addCriterion("myId is null");
			return (Criteria) this;
		}

		public Criteria andMyidIsNotNull() {
			addCriterion("myId is not null");
			return (Criteria) this;
		}

		public Criteria andMyidEqualTo(Integer value) {
			addCriterion("myId =", value, "myid");
			return (Criteria) this;
		}

		public Criteria andMyidNotEqualTo(Integer value) {
			addCriterion("myId <>", value, "myid");
			return (Criteria) this;
		}

		public Criteria andMyidGreaterThan(Integer value) {
			addCriterion("myId >", value, "myid");
			return (Criteria) this;
		}

		public Criteria andMyidGreaterThanOrEqualTo(Integer value) {
			addCriterion("myId >=", value, "myid");
			return (Criteria) this;
		}

		public Criteria andMyidLessThan(Integer value) {
			addCriterion("myId <", value, "myid");
			return (Criteria) this;
		}

		public Criteria andMyidLessThanOrEqualTo(Integer value) {
			addCriterion("myId <=", value, "myid");
			return (Criteria) this;
		}

		public Criteria andMyidIn(List<Integer> values) {
			addCriterion("myId in", values, "myid");
			return (Criteria) this;
		}

		public Criteria andMyidNotIn(List<Integer> values) {
			addCriterion("myId not in", values, "myid");
			return (Criteria) this;
		}

		public Criteria andMyidBetween(Integer value1, Integer value2) {
			addCriterion("myId between", value1, value2, "myid");
			return (Criteria) this;
		}

		public Criteria andMyidNotBetween(Integer value1, Integer value2) {
			addCriterion("myId not between", value1, value2, "myid");
			return (Criteria) this;
		}

		public Criteria andFriendidIsNull() {
			addCriterion("friendId is null");
			return (Criteria) this;
		}

		public Criteria andFriendidIsNotNull() {
			addCriterion("friendId is not null");
			return (Criteria) this;
		}

		public Criteria andFriendidEqualTo(Integer value) {
			addCriterion("friendId =", value, "friendid");
			return (Criteria) this;
		}

		public Criteria andFriendidNotEqualTo(Integer value) {
			addCriterion("friendId <>", value, "friendid");
			return (Criteria) this;
		}

		public Criteria andFriendidGreaterThan(Integer value) {
			addCriterion("friendId >", value, "friendid");
			return (Criteria) this;
		}

		public Criteria andFriendidGreaterThanOrEqualTo(Integer value) {
			addCriterion("friendId >=", value, "friendid");
			return (Criteria) this;
		}

		public Criteria andFriendidLessThan(Integer value) {
			addCriterion("friendId <", value, "friendid");
			return (Criteria) this;
		}

		public Criteria andFriendidLessThanOrEqualTo(Integer value) {
			addCriterion("friendId <=", value, "friendid");
			return (Criteria) this;
		}

		public Criteria andFriendidIn(List<Integer> values) {
			addCriterion("friendId in", values, "friendid");
			return (Criteria) this;
		}

		public Criteria andFriendidNotIn(List<Integer> values) {
			addCriterion("friendId not in", values, "friendid");
			return (Criteria) this;
		}

		public Criteria andFriendidBetween(Integer value1, Integer value2) {
			addCriterion("friendId between", value1, value2, "friendid");
			return (Criteria) this;
		}

		public Criteria andFriendidNotBetween(Integer value1, Integer value2) {
			addCriterion("friendId not between", value1, value2, "friendid");
			return (Criteria) this;
		}

		public Criteria andFriendremarksIsNull() {
			addCriterion("friendRemarks is null");
			return (Criteria) this;
		}

		public Criteria andFriendremarksIsNotNull() {
			addCriterion("friendRemarks is not null");
			return (Criteria) this;
		}

		public Criteria andFriendremarksEqualTo(String value) {
			addCriterion("friendRemarks =", value, "friendremarks");
			return (Criteria) this;
		}

		public Criteria andFriendremarksNotEqualTo(String value) {
			addCriterion("friendRemarks <>", value, "friendremarks");
			return (Criteria) this;
		}

		public Criteria andFriendremarksGreaterThan(String value) {
			addCriterion("friendRemarks >", value, "friendremarks");
			return (Criteria) this;
		}

		public Criteria andFriendremarksGreaterThanOrEqualTo(String value) {
			addCriterion("friendRemarks >=", value, "friendremarks");
			return (Criteria) this;
		}

		public Criteria andFriendremarksLessThan(String value) {
			addCriterion("friendRemarks <", value, "friendremarks");
			return (Criteria) this;
		}

		public Criteria andFriendremarksLessThanOrEqualTo(String value) {
			addCriterion("friendRemarks <=", value, "friendremarks");
			return (Criteria) this;
		}

		public Criteria andFriendremarksLike(String value) {
			addCriterion("friendRemarks like", value, "friendremarks");
			return (Criteria) this;
		}

		public Criteria andFriendremarksNotLike(String value) {
			addCriterion("friendRemarks not like", value, "friendremarks");
			return (Criteria) this;
		}

		public Criteria andFriendremarksIn(List<String> values) {
			addCriterion("friendRemarks in", values, "friendremarks");
			return (Criteria) this;
		}

		public Criteria andFriendremarksNotIn(List<String> values) {
			addCriterion("friendRemarks not in", values, "friendremarks");
			return (Criteria) this;
		}

		public Criteria andFriendremarksBetween(String value1, String value2) {
			addCriterion("friendRemarks between", value1, value2,
					"friendremarks");
			return (Criteria) this;
		}

		public Criteria andFriendremarksNotBetween(String value1, String value2) {
			addCriterion("friendRemarks not between", value1, value2,
					"friendremarks");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNull() {
			addCriterion("username is null");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNotNull() {
			addCriterion("username is not null");
			return (Criteria) this;
		}

		public Criteria andUsernameEqualTo(String value) {
			addCriterion("username =", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotEqualTo(String value) {
			addCriterion("username <>", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThan(String value) {
			addCriterion("username >", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThanOrEqualTo(String value) {
			addCriterion("username >=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThan(String value) {
			addCriterion("username <", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThanOrEqualTo(String value) {
			addCriterion("username <=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLike(String value) {
			addCriterion("username like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotLike(String value) {
			addCriterion("username not like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameIn(List<String> values) {
			addCriterion("username in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotIn(List<String> values) {
			addCriterion("username not in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameBetween(String value1, String value2) {
			addCriterion("username between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotBetween(String value1, String value2) {
			addCriterion("username not between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andPicIsNull() {
			addCriterion("pic is null");
			return (Criteria) this;
		}

		public Criteria andPicIsNotNull() {
			addCriterion("pic is not null");
			return (Criteria) this;
		}

		public Criteria andPicEqualTo(String value) {
			addCriterion("pic =", value, "pic");
			return (Criteria) this;
		}

		public Criteria andPicNotEqualTo(String value) {
			addCriterion("pic <>", value, "pic");
			return (Criteria) this;
		}

		public Criteria andPicGreaterThan(String value) {
			addCriterion("pic >", value, "pic");
			return (Criteria) this;
		}

		public Criteria andPicGreaterThanOrEqualTo(String value) {
			addCriterion("pic >=", value, "pic");
			return (Criteria) this;
		}

		public Criteria andPicLessThan(String value) {
			addCriterion("pic <", value, "pic");
			return (Criteria) this;
		}

		public Criteria andPicLessThanOrEqualTo(String value) {
			addCriterion("pic <=", value, "pic");
			return (Criteria) this;
		}

		public Criteria andPicLike(String value) {
			addCriterion("pic like", value, "pic");
			return (Criteria) this;
		}

		public Criteria andPicNotLike(String value) {
			addCriterion("pic not like", value, "pic");
			return (Criteria) this;
		}

		public Criteria andPicIn(List<String> values) {
			addCriterion("pic in", values, "pic");
			return (Criteria) this;
		}

		public Criteria andPicNotIn(List<String> values) {
			addCriterion("pic not in", values, "pic");
			return (Criteria) this;
		}

		public Criteria andPicBetween(String value1, String value2) {
			addCriterion("pic between", value1, value2, "pic");
			return (Criteria) this;
		}

		public Criteria andPicNotBetween(String value1, String value2) {
			addCriterion("pic not between", value1, value2, "pic");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table friend
	 * @mbggenerated  Sun Jul 09 14:37:52 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table friend
     *
     * @mbggenerated do_not_delete_during_merge Thu Jul 06 00:40:11 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}