package com.ws.model;

public class FriendKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.myId
     *
     * @mbggenerated Thu Jul 06 00:40:11 CST 2017
     */
    private Integer myid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.friendId
     *
     * @mbggenerated Thu Jul 06 00:40:11 CST 2017
     */
    private Integer friendid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.myId
     *
     * @return the value of friend.myId
     *
     * @mbggenerated Thu Jul 06 00:40:11 CST 2017
     */
    public Integer getMyid() {
        return myid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.myId
     *
     * @param myid the value for friend.myId
     *
     * @mbggenerated Thu Jul 06 00:40:11 CST 2017
     */
    public void setMyid(Integer myid) {
        this.myid = myid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.friendId
     *
     * @return the value of friend.friendId
     *
     * @mbggenerated Thu Jul 06 00:40:11 CST 2017
     */
    public Integer getFriendid() {
        return friendid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.friendId
     *
     * @param friendid the value for friend.friendId
     *
     * @mbggenerated Thu Jul 06 00:40:11 CST 2017
     */
    public void setFriendid(Integer friendid) {
        this.friendid = friendid;
    }
}