package com.ws.model;

public class Friend extends FriendKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.friendRemarks
     *
     * @mbggenerated Thu Jul 06 00:40:11 CST 2017
     */
    private String friendremarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.friendRemarks
     *
     * @return the value of friend.friendRemarks
     *
     * @mbggenerated Thu Jul 06 00:40:11 CST 2017
     */
    public String getFriendremarks() {
        return friendremarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.friendRemarks
     *
     * @param friendremarks the value for friend.friendRemarks
     *
     * @mbggenerated Thu Jul 06 00:40:11 CST 2017
     */
    public void setFriendremarks(String friendremarks) {
        this.friendremarks = friendremarks;
    }
}