package com.ws.mapper;

import com.ws.model.Addfriendinfo;
import com.ws.model.AddfriendinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AddfriendinfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table addfriendinfo
	 * @mbggenerated  Fri Jul 07 16:24:03 CST 2017
	 */
	int countByExample(AddfriendinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table addfriendinfo
	 * @mbggenerated  Fri Jul 07 16:24:03 CST 2017
	 */
	int deleteByExample(AddfriendinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table addfriendinfo
	 * @mbggenerated  Fri Jul 07 16:24:03 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table addfriendinfo
	 * @mbggenerated  Fri Jul 07 16:24:03 CST 2017
	 */
	int insert(Addfriendinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table addfriendinfo
	 * @mbggenerated  Fri Jul 07 16:24:03 CST 2017
	 */
	int insertSelective(Addfriendinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table addfriendinfo
	 * @mbggenerated  Fri Jul 07 16:24:03 CST 2017
	 */
	List<Addfriendinfo> selectByExample(AddfriendinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table addfriendinfo
	 * @mbggenerated  Fri Jul 07 16:24:03 CST 2017
	 */
	Addfriendinfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table addfriendinfo
	 * @mbggenerated  Fri Jul 07 16:24:03 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Addfriendinfo record,
			@Param("example") AddfriendinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table addfriendinfo
	 * @mbggenerated  Fri Jul 07 16:24:03 CST 2017
	 */
	int updateByExample(@Param("record") Addfriendinfo record,
			@Param("example") AddfriendinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table addfriendinfo
	 * @mbggenerated  Fri Jul 07 16:24:03 CST 2017
	 */
	int updateByPrimaryKeySelective(Addfriendinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table addfriendinfo
	 * @mbggenerated  Fri Jul 07 16:24:03 CST 2017
	 */
	int updateByPrimaryKey(Addfriendinfo record);
}