package com.ws.mapper;

import com.ws.model.Friend;
import com.ws.model.FriendExample;
import com.ws.model.FriendKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FriendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbggenerated Thu Jul 06 00:40:11 CST 2017
     */
    int countByExample(FriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbggenerated Thu Jul 06 00:40:11 CST 2017
     */
    int deleteByExample(FriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbggenerated Thu Jul 06 00:40:11 CST 2017
     */
    int deleteByPrimaryKey(FriendKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbggenerated Thu Jul 06 00:40:11 CST 2017
     */
    int insert(Friend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbggenerated Thu Jul 06 00:40:11 CST 2017
     */
    int insertSelective(Friend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbggenerated Thu Jul 06 00:40:11 CST 2017
     */
    List<Friend> selectByExample(FriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbggenerated Thu Jul 06 00:40:11 CST 2017
     */
    Friend selectByPrimaryKey(FriendKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbggenerated Thu Jul 06 00:40:11 CST 2017
     */
    int updateByExampleSelective(@Param("record") Friend record, @Param("example") FriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbggenerated Thu Jul 06 00:40:11 CST 2017
     */
    int updateByExample(@Param("record") Friend record, @Param("example") FriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbggenerated Thu Jul 06 00:40:11 CST 2017
     */
    int updateByPrimaryKeySelective(Friend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbggenerated Thu Jul 06 00:40:11 CST 2017
     */
    int updateByPrimaryKey(Friend record);
}